--liquibase formatted sql
--changeset ruslan:create-actor-table.sql:true endDelimiter:;

CREATE TABLE actors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES countries(id)
);

--rollback DROP TABLE actors;