--liquibase formatted sql
--changeset ruslan:create-country-table.sql:true endDelimiter:;

CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

--rollback DROP TABLE countries;