--liquidbase formatted sql
CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        title VARCHAR(255),
                        PRIMARY KEY (id)
)