--liquibase formatted sql
--changeset yaroslav:create-country-table endDelimiter:;

CREATE TABLE IF NOT EXISTS countries (
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (id));

--rollback DROP TABLE countries;