--liquibase formatted sql
--changeset yuriykhilko:create-actors-table splitStatements:true endDelimiter:;

create table actors (country_id bigint, id bigint generated by default as identity (start with 1), name varchar(255), primary key (id));
--create table actors (id bigint not null auto_increment, name varchar(255), country_id bigint, primary key (id)) engine=MyISAM;

--rollback DROP TABLE actors;