--liquibase formatted sql
--changeset yaroslav:create-actor-table endDelimiter:;

CREATE TABLE IF NOT EXISTS actors (
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255) DEFAULT NULL,
country_id BIGINT DEFAULT NULL,
PRIMARY KEY (id),
CONSTRAINT actors_countries_fk
FOREIGN KEY (country_id)
REFERENCES countries (id));

--rollback DROP TABLE actors;