--liquibase formatted sql
--changeset yaroslav:create-movie-table endDelimiter:;

CREATE TABLE IF NOT EXISTS movies (
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (id));

--rollback DROP TABLE movies;