--liquibase formatted sql
--changeset yuriykhilko:create-counties-table splitStatements:true endDelimiter:;

create table countries (id bigint generated by default as identity (start with 0), name varchar(255), primary key (id));

--rollback DROP TABLE countries;