--liquibase formatted sql
--changeset ruslan:create-movie-table.sql:true endDelimiter:;

CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255)
);

CREATE TABLE movies_actors (
    movie_id BIGINT,
    actor_id BIGINT,
    FOREIGN KEY (movie_id) REFERENCES movies(id),
    FOREIGN KEY (actor_id) REFERENCES actors(id)
);

--rollback DROP TABLE movies;
--rollback DROP TABLE movies_actors;