CREATE TABLE actors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        country_id BIGINT,
                        FOREIGN KEY (country_id) REFERENCES countries(id)
);