--liquibase formatted sql
--changeset AdamMudrak:create-actors-table
--Use AUTO_INCREMENT for MySQL or GENERATED BY DEFAULT AS IDENTITY for HSQLDB
CREATE TABLE actors (
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(255),
country_id BIGINT,
PRIMARY KEY (id))