--liquibase formatted sql
--changeset AdamMudrak:create-movies-table
--Use AUTO_INCREMENT for MySQL or GENERATED BY DEFAULT AS IDENTITY for HSQLDB
CREATE TABLE movies (
id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR(255),
PRIMARY KEY (id))