--liquibase formatted sql

--changeset klickice:create-countries-table splitStatements:true endDelimiter:;
CREATE TABLE countries (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255)
);
