--liquibase formatted sql

--changeset klickice:create-movies-table splitStatements:true endDelimiter:;
CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255)
);
